version: '3.8'
services:
    plan-mysql:
        image: cozzz/mysql
        volumes:
            - ./data/mysql/:/var/lib/mysql/:rw
            - ./log/mysql/:/var/lib/mysql-logs/:rw
        environment:
            MYSQL_ROOT_PASSWORD: 1qaz123
            MYSQL_DATABASE: plan
        restart: always
        command: "--character-set-server=utf8"

    plan-server:
        build:
            context: ../
            dockerfile: docker-env/server/Dockerfile
        depends_on:
            - plan-mysql
        container_name: plan-server
        restart: always
        # command: node /run/app/dist/main.js



