version: '3.8'
services:
    mysql:
        image: cozzz/mysql
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql/:/var/lib/mysql/:rw
            - ./log/mysql/:/var/lib/mysql-logs/:rw
        environment:
            MYSQL_ROOT_PASSWORD: 1qaz123
            MYSQL_DATABASE: plan
        restart: always
        command: "--character-set-server=utf8"

    nginx:
        image: cozzz/nginx
        depends_on:
            - mysql
            - nodejs
        volumes:
            - ../../:/run/app/:rw
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:rw
            - ./nginx/conf/conf.d/:/etc/nginx/conf.d/:rw
            - ./log/docker/nginx/:/var/log/nginx/:rw
        ports:
            - "80:80"
        restart: always
        command: nginx -g 'daemon off;'

    nodejs:
        build:
            context: ../
            dockerfile: docker-env/server/Dockerfile
        # image: node:12-alpine3.10
        container_name: nodejs
        restart: always
        command: node /run/app/dist/main.js

    node-env:
        build:
            context: .
            dockerfile: node/Dockerfile
        container_name: node-env
        volumes:
            - ../../:/run/app/:rw
        restart: always
        tty: true

